CREATE TRIGGER SUB_ID_BIR BEFORE INSERT 
ON SUBDIVISIONS FOR EACH ROW
WHEN (NEW.SUB_ID IS NULL)
BEGIN 
	:NEW.SUB_ID:=SUB_ID_SEQ.NEXTVAL
	:NEW.SUB_NAME:=UPPER(:NEW.SUB_NAME)
	:NEW.SUB_ROLE:=UPPER(:NEW.SUB_ROLE)
END;

CREATE TRIGGER POS_ID_BIR BEFORE INSERT
ON POSITIONS FOR EACH ROW
WHEN (NEW.POS_ID IS NULL)
BEGIN
	:NEW.POS_ID:=POS_ID_SEQ.NEXTVAL
	:NEW.POS_NAME:=UPPER(:NEW.POS_NAME)
END;

CREATE TRIGGER EMP_ID_BIR BEFORE INSERT
ON EMPLOYEES FOR EACH ROW
WHEN (NEW.EMP_ID IS NULL)
BEGIN
	:NEW.EMP_ID:=EMP_ID_SEQ.NEXTVAL
	:NEW.EMP_FULL_NAME:=UPPER(:NEW.EMP_FULL_NAME)
	:NEW.EMP_PASSPORT:=UPPER(:NEW.EMP_PASSPORT)
END;

CREATE TRIGGER ABS_ID_BIR BEFORE INSERT
ON ABSENCE FOR EACH ROW
WHEN (NEW.ABS_ID IS NULL)
BEGIN
	:NEW.ABS_ID:=ABS_ID_SEQ.NEXTVAL
	:NEW.ABS_NAME:=UPPER(:NEW.ABS_NAME)
END;

CREATE TRIGGER TIMETABLE_ID_BIR BEFORE INSERT
ON TIMETABLE FOR EACH ROW
WHEN (NEW.TIME_ID IS NULL)
BEGIN
	:NEW.TIME_ID:=TIME_ID_SEQ.NEXTVAL
	:NEW.TIME_DATE:=TRUNC(:NEW.TIME_DATE)
END;

CREATE TRIGGER SO_ID_BIR BEFORE INSERT
ON STAFF_ORDER_HEADER FOR EACH ROW
WHEN (NEW.SO_ID IS NULL)
BEGIN
	:NEW.SO_ID:=SO_ID_SEQ.NEXTVAL
	:NEW.SO_NUMBER:=UPPER(:NEW.SO_NUMBER)
END;

CREATE TRIGGER SOL_ID_BIR BEFORE INSERT
ON STAFF_ORDER_LINES FOR EACH ROW
WHEN (NEW.SOL_ID IS NULL)
BEGIN
	:NEW.SOL_ID:=SOL_ID_SEQ.NEXTVAL
END;

CREATE TRIGGER AE_ID_BIR BEFORE INSERT
ON ABSENCE_EMPLOYEE FOR EACH ROW
WHEN (NEW.AE_ID IS NULL)
BEGIN
	:NEW.AE_ID:=AE_ID_SEQ.NEXTVAL
	:NEW.AE_NUMBER:=UPPER(:NEW.AE_NUMBER)
END;

CREATE TRIGGER CS_ID_BIR BEFORE INSERT
ON CALC_SALARY_HEADER FOR EACH ROW
WHEN (NEW.CS_ID IS NULL)
BEGIN
	:NEW.CS_ID:=CS_ID_SEQ.NEXTVAL
	:NEW.CS_NUMBER:=UPPER(:NEW.CS_NUMBER)
END;

CREATE TRIGGER COUNT_SAL_LINES_ID BEFORE INSERT
ON CALC_SALARY_LINES FOR EACH ROW
WHEN (NEW.CSL_ID IS NULL)
BEGIN
	:NEW.CSL_ID:=CSL_ID_SEQ.NEXTVAL
END;