CREATE OR REPLACE VIEW POSITIONS_EMPLOYEES_VIEW AS
SELECT T1.POS_ID,T1.EMP_ID,T1.SUB_ID,T1.RATE,T1.SALARY,T1.PE_STATE,T1.PE_VALID_SINCE,NVL(MIN(T2.PE_VALID_SINCE-1),TO_DATE('31.12.2099','DD.MM.YYYY')) AS VALID_UNTIL
FROM POSITIONS_EMPLOYEES T1 LEFT OUTER JOIN POSITIONS_EMPLOYEES T2 ON
T1.POS_ID=T2.POS_ID AND
T1.EMP_ID=T2.EMP_ID AND
T1.SUB_ID=T2.SUB_ID AND
T1.RATE=T2.RATE AND
T1.SALARY=T2.SALARY AND
T1.PE_VALID_SINCE<T2.PE_VALID_SINCE
  
GROUP BY T1.POS_ID,T1.EMP_ID,T1.SUB_ID,T1.RATE,T1.SALARY,T1.PE_STATE,T1.PE_VALID_SINCE
ORDER BY T1.VALID_SINCE,T1.SUB_ID,T1.EMP_ID,T1.POS_ID,T1.RATE,T1.SALARY,T1.PE_STATE;